CREATE TABLE "GCG_4980_MAT_HIST" (
 "NEST_ID" CHAR(40),
 "RECORD_ID" INTEGER,
 "MATERIAL" CHAR(20),
 "LOCATION" CHAR(2),
 "UM" CHAR(2),
 "TOTAL_MATERIAL" DOUBLE,
 "ISSUED" DOUBLE,
 "FLEX_SCHEDULE" CHAR(6),
 "NEXT_FLEX_SCHEDULE" CHAR(6),
 "PROFILE" CHAR(10),
 "POST_TIMESTAMP" DATETIME,
 "SHEET_AREA" DOUBLE,
 "SHEET_WEIGHT" DOUBLE );
