CREATE TABLE "GCG_4980_NESTMAINT" (
 "XPTYPE" CHAR(1),
 "ENABLED" BIT NOT NULL,
 "XPFIELD" CHAR(50),
 "MAPID" CHAR(4),
 "HARDCODE_VALUE" VARCHAR(50),
 "INDX" INTEGER NOT NULL,
 "PROFILE" CHAR(10),
 "XML_PATH" LONGVARCHAR );